name: CI - Maven Selenium Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show versions
        run: |
          google-chrome --version || true
          chromedriver --version || true

      - name: Run tests (Maven)
        env:
          CI: "true"
          HEADLESS: "true"
        run: mvn -B -U clean test

      - name: Upload surefire-reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.java }}
          path: |
            **/target/surefire-reports/*
            **/target/failsafe-reports/*
